"""storage

Revision ID: 081ef2fb5209
Revises: 
Create Date: 2019-09-09 17:02:02.416077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081ef2fb5209'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stored_file')
    # ### end Alembic commands ###
